services:
  logger:
    build:
      context: .
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    expose:
      - 1883
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

configs:
  mosquitto_config:
    file: ./mosquitto/config/mosquitto.conf