services:
  logger:
    build:
      context: .
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    expose:
      - 1883
    volumes:
      - ./mosquitto/config:/mosquitto/config