services:
  logger:
    build:
      context: .
      dockerfile: ./images/logger.Dockerfile
    depends_on:
      - mosquitto

  mosquitto:
    build:
      context: .
      dockerfile: ./images/mosquitto.Dockerfile
    expose:
      - 1883
    volumes:
      - ./mosquitto/config:/mosquitto/config